name: deploy backend

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/place-mark-api/**'
      - '*.json'
      - '*.yml'

jobs:
  update-database:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: NPM CI
        working-directory: ./packages/place-mark-api
        run: npm ci

      - name: Create .env File
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.PRODUCTION_CONNECTION_STRING }}
          directory: ./packages/place-mark-api

      - name: Push Database
        working-directory: ./packages/place-mark-api
        run: npx prisma db push

      - name: Seed Database
        working-directory: ./packages/place-mark-api
        run: npm run seed