name: deploy-web

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/place-mark-web/**'
      - '*.json'

jobs:
  deploy-frontend:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: NPM CI
        run: npm ci

      - name: NPM Build
        run: npm run build:web

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './packages/place-mark-web/dist'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.PRODUCTION_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PRODUCTION_NETLIFY_SITE_ID }}
        timeout-minutes: 1