name: test-backend-staging

on:
  #  push:
  #    branches:
  #      - 'main'
  pull_request:
#    paths:
#      - 'packages/place-mark-api/**'
#      - '*.json'

jobs:
  test-backend-cloud-atlas:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: NPM CI
        run: npm ci

      - name: Create .env File
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_COOKIE_PASSWORD: ${{ secrets.STAGING_COOKIE_PASSWORD }}
          envkey_JWT_PASSWORD: ${{ secrets.STAGING_JWT_PASSWORD }}
          envkey_DATABASE_URL: ${{ secrets.STAGING_CONNECTION_STRING }}
          directory: ./packages/place-mark-api

      - name: Create .env.testing File
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.STAGING_CONNECTION_STRING }}
          directory: ./packages/place-mark-api
          file_name: .env.testing

      - name: Tests
        run: npm run test:api

  deploy-frontend:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: NPM CI
        run: npm ci

      - name: NPM Build
        run: npm run build:web

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './packages/place-mark-web/dist'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.PRODUCTION_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PRODUCTION_NETLIFY_SITE_ID }}
        timeout-minutes: 1